debug:

logger:
    level: DEBUG
    baud_rate: 0

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      id: heap_free
    block:
      name: "Heap Max Block"
      id: heap_max_block
    loop_time:
      name: "Loop Time"
      id: loop_time
  - platform: uptime
    name: Uptime Sensor
text_sensor:
  - platform: debug
    device:
      name: "Device Info"
   reset_reason:
      name: "Reset Reason"

# # UART0 configuration for AUX air conditioner communication
uart:
  id: ac_uart_bus
  # ATTENTION! Use GPIO4 (D2) and GPIO5 (D1) as the TX and RX for NodeMCU-like boards!
  tx_pin: GPIO3  # ${tx_pin_aux}
  rx_pin: GPIO1 # ${rx_pin_aux}
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1
climate:
  - platform: aux_ac
    name: ${upper_devicename}
    id: aux_id
    uart_id: ac_uart_bus
    period: 7s
    show_action: true
    display_inverted: true
    optimistic: true
    indoor_temperature:
      name: ${upper_devicename} Indoor Temperature
      id: ac_indoor_temp
      internal: false
    display_state:
      name: ${upper_devicename} Display State
      id: ac_display_state
      internal: false
    outdoor_temperature:
      name: ${upper_devicename} Outdoor Temperature
      id: ac_outdoor_temp
      internal: false
    outbound_temperature:
      name: ${upper_devicename} Coolant Outbound Temperature
      id: ac_outbound_temp
      internal: false
    inbound_temperature:
      name: ${upper_devicename} Coolant Inbound Temperature
      id: ac_inbound_temp
      internal: false
    compressor_temperature:
      name: ${upper_devicename} Compressor Temperature
      id: ac_strange_temp
      internal: false
    defrost_state:
      name: ${upper_devicename} Defrost State
      id: ac_defrost_state
      internal: false
    inverter_power:
      name: ${upper_devicename} Invertor Power
      id: ac_inverter_power
      internal: false
    preset_reporter:
      name: ${upper_devicename} Preset Reporter
      id: ac_preset_reporter
      internal: false
    vlouver_state:
      name: ${upper_devicename} VLouvers State
      id: ac_vlouver_state
      internal: false
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 0.5
    supported_modes:
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    custom_fan_modes:
      - MUTE
      - TURBO
    supported_presets:
      - SLEEP
    custom_presets:
      - CLEAN
      - HEALTH
      - ANTIFUNGUS
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH


sensor:
  # just wifi signal strength for debug purpose only
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    update_interval: 30s
    unit_of_measurement: "dBa"
    accuracy_decimals: 0


switch:
  - platform: template
    name: ${upper_devicename} Display
    lambda: |-
      if (id(${lower_devicename}_display_state).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - aux_ac.display_on: aux_id
    turn_off_action:
      - aux_ac.display_off: aux_id

button:
  - platform: template
    name: ${upper_devicename} VLouver Stop
    icon: "mdi:circle-small"
    on_press:
      - aux_ac.vlouver_stop: aux_id
    
  - platform: template
    name: ${upper_devicename} VLouver Swing
    icon: "mdi:pan-vertical"
    on_press:
      - aux_ac.vlouver_swing: aux_id
    
  - platform: template
    name: ${upper_devicename} VLouver Top
    icon: "mdi:pan-up"
    on_press:
      - aux_ac.vlouver_top: aux_id
    
  - platform: template
    name: ${upper_devicename} VLouver Middle Above
    icon: "mdi:pan-top-left"
    on_press:
      - aux_ac.vlouver_middle_above: aux_id
    
  - platform: template
    name: ${upper_devicename} VLouver Middle
    icon: "mdi:pan-left"
    on_press:
      - aux_ac.vlouver_middle: aux_id
    
  - platform: template
    name: ${upper_devicename} VLouver Middle Below
    icon: "mdi:pan-bottom-left"
    on_press:
      - aux_ac.vlouver_middle_below: aux_id
    
  - platform: template
    name: ${upper_devicename} VLouver Bottom
    icon: "mdi:pan-down"
    on_press:
      - aux_ac.vlouver_bottom: aux_id


number:
  - platform: template
    name: ${upper_devicename} Vertical Louvers
    id: ac_vlouver
    icon: "mdi:circle-small"
    mode: "slider"
    min_value: 0
    max_value: 6
    step: 1
    update_interval: 2s
    lambda: |-
      return id(${lower_devicename}_vlouver_state).state;
    set_action:
      then:
        - aux_ac.vlouver_set:
            id: aux_id
            position: !lambda "return x;"

  - platform: template
    name: ${upper_devicename} Power Limit
    id: ac_power_limit
    icon: "mdi:battery-unknown"
    mode: "slider"
    min_value: 30
    max_value: 100
    step: 1
    set_action:
      then:
        - lambda: !lambda "id(aux_id).powerLimitationOnSequence( x );"
